### ISSUE TITLE
EasyEDA or KiCad etc. project?

### ISSUE THREAD

**Issue by mjcargill** [JDet-74/C128_U36_adapter#2]
Hi,

I'd like to build a couple of these and wondered if you had the project/schematics available so that I can generate the pick and place files to get them built and the components done via an SMT service?

Many thanks,

**Comment by JDet-74** [comment]
Hi, 
I designed this version (ICs on both PCB sides) in Eagle. Do SMT service work on both sides?
If you want, I can publish the eagle files.

Cheers

**Comment by mjcargill** [comment]
Hi,

Not all services will do both sides (there are some but expensive), but I can get most of it done (topside) and only have one chip to solder underneath – save me a bit of time 😊

If you could publish the Eagle files, that would be amazing!

Many thanks,

**Comment by JDet-74** [comment]
Eagel files are published ... use them ... improve them ... have fun :)

**Comment by mjcargill** [comment]
Thanks!  I will! :-)

**Comment by mjcargill** [comment]
Hi,

Not all services will do both sides (there are some but expensive), but I can get most of it done (topside) and only have one chip to solder underneath – save me a bit of time 😊

If you could publish the Eagle files, that would be amazing!

Many thanks,

Mark.
